-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 16:48:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce1` ;

-- -----------------------------------------------------
-- Table `ecommerce1`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`address` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `pincode` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `type_of_address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce1`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce1`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME(6) NULL DEFAULT NULL,
  `last_updated` DATETIME(6) NULL DEFAULT NULL,
  `order_tracking_number` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `total_price` DECIMAL(38,2) NULL DEFAULT NULL,
  `total_quantity` INT NULL DEFAULT NULL,
  `billing_address_id` BIGINT NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `shipping_address_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKitkimh4jcikj0wxjqj47ec27f` (`billing_address_id` ASC) VISIBLE,
  UNIQUE INDEX `UKg6t4cupq8aflsrymgl4234yba` (`shipping_address_id` ASC) VISIBLE,
  INDEX `FKk1m6gjs4m7rtgb5lw01g35yca` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FK6t14cnj3gpbmex9ubl7hrnb0e`
    FOREIGN KEY (`billing_address_id`)
    REFERENCES `ecommerce1`.`address` (`id`),
  CONSTRAINT `FKjc6yc0p0n80mgdj0dqp7suhqg`
    FOREIGN KEY (`shipping_address_id`)
    REFERENCES `ecommerce1`.`address` (`id`),
  CONSTRAINT `FKk1m6gjs4m7rtgb5lw01g35yca`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ecommerce1`.`customer` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce1`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `unit_price` DECIMAL(38,2) NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKl1bqqbilx1hdy29vykrqkgu3p` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKl1bqqbilx1hdy29vykrqkgu3p`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce1`.`order` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce1`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce1`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NULL DEFAULT NULL,
  `date_created` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `last_updated` DATETIME(6) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `sku` VARCHAR(255) NULL DEFAULT NULL,
  `unit_price` VARCHAR(255) NULL DEFAULT NULL,
  `units_in_stock` INT NULL DEFAULT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7l29ekt1x29jup80y2iigimyy` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK7l29ekt1x29jup80y2iigimyy`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecommerce1`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
